// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO2-8m9CB-AXfjwSjOTWr0Yili6c4MSZY',
    appId: '1:270070427709:web:41e8ac3acaae1ff6baba54',
    messagingSenderId: '270070427709',
    projectId: 'fittrack-25030',
    authDomain: 'fittrack-25030.firebaseapp.com',
    storageBucket: 'fittrack-25030.firebasestorage.app',
    measurementId: 'G-PTS1NZ262S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5CI9iIFP29SgZBigdwYiUkKhn6oeol0',
    appId: '1:270070427709:android:3bad11528248a5d1baba54',
    messagingSenderId: '270070427709',
    projectId: 'fittrack-25030',
    storageBucket: 'fittrack-25030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYv9gbRe4hUMDPsFjRABn8IWRlEDjZgVI',
    appId: '1:270070427709:ios:67147429d3d608bbbaba54',
    messagingSenderId: '270070427709',
    projectId: 'fittrack-25030',
    storageBucket: 'fittrack-25030.firebasestorage.app',
    iosBundleId: 'com.example.fittrack',
  );
}
